name: Testing the actions
on:
  push:
    branches:
      - main # Change to main to trigger the workflow.
  # TODO:
  # Update jsonReader and jsonWriter: Must fetch from a branch before reading and writing.

jobs:
  find-project-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/findprojectversion
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
      - run: |
          echo "Result: ${{ steps.json.outputs.value }}"
    # Input: branch
    # Update: Fetch given branch.

  set-project-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo.
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: ./.github/actions/setprojectversion
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
          value: "11.1.0"
          # TODO:
          # Update jsonWriter: [Fetch given branch], [Commit and push the update file to branch].
          # Add inputs:
          # Branch.
          # email - global user.email
          # name - global user.name

      - name: commit changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}"
          git add ./.github/resources/testVersions.json
          git commit -m "Update versions"
          git push

      # git push origin HEAD:main
      # git fetch origin main
