name: Testing the actions
on:
  push:
    branches:
      - main # Change to main to trigger the workflow.
  # TODO:
  # Update jsonReader and jsonWriter: Must fetch from a branch before reading and writing.

jobs:
  find-project-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/jsonReader
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
      - run: |
          echo "Result: ${{ steps.json.outputs.value }}"
      # Input: branch
    # Update: Fetch given branch.

  set-project-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setprojectversion
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
          value: "11.1.0"
          # TODO:
          # Update jsonWriter: [Fetch given branch], [Commit and push the update file to branch].
          # Add inputs:
          # Branch.
          # email - global user.email
          # name - global user.name
      - run: |
          echo "Result: ${{ steps.json.outputs.map }}"
          git diff ./.github/resources/testVersions.json
          git config --global user.email "abdullahi.aden.hassan@gmail.com"
          git config --global user.name "AbdullahiAdenHassan"
          git add -A
          git commit -m "Update core in version"
          git push
      # git push origin HEAD:main
      # git fetch origin main
