name: Testing the actions
on:
  push:
    branches:
      - main # Change to main to trigger the workflow.

jobs:
  testing-jsonReader-1:
    needs: testing-jsonWriter-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/jsonReader
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
      - run: |
          echo "Result: ${{ steps.json.outputs.value }}"

  testing-jsonReader-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/jsonReader
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "adp"
      - run: |
          echo "Result: ${{ steps.json.outputs.value }}"

  testing-jsonWriter-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/jsonWriter
        id: json
        with:
          path: "./.github/resources/testVersions.json"
          key: "core"
          value: "11.0.11"
      - run: |
          echo "Result: ${{ steps.json.outputs.map }}"
          git diff ./.github/resources/testVersions.json
          git config --global user.email "abdullahi.aden.hassan@gmail.com"
          git config --global user.name "AbdullahiAdenHassan"
          git add -A
          git commit -m "Update core in version"
          git fetch origin main
          git push origin HEAD:master
