name: Testing the actions
on:
  push:
    branches:
      - main # Change to main to trigger the workflow.

jobs:
  testing-jsonReader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/jsonReader
        id: json
        with:
          json-file: "./.github/resources/testVersions.json"
          key: "core"
      - run: |
          echo "Result: ${{ steps.json.outputs.value }}"
